local core = luajava.getCore()
local manager = core:getRootManager()
local window = core:getUID()
manager:addWindow(100, 100, 100, 25, window)
manager:getWindow(window):updateStyle("FREE")
manager:getWindow(window):addMouseRegion("INTERNALDRAG", "", 5,5,10,10)
manager:windowSurface(window):setColor(core:createColor(0,0,0))
manager:windowSurface(window):fillRect(0,0,100,25)
manager:windowSurface(window):setColor(core:createColor(0,0,255))
manager:windowSurface(window):fillRect(5,5,10,10)
manager:windowSurface(window):setColor(core:createColor(0,255,0))
manager:windowSurface(window):fillRect(0,0,100,25)
manager:getWindow(window):updateStyle("NORMAL")
